import {
  Box,
  Button,
  Container,
  Divider,
  Skeleton,
  Stack,
  Typography,
} from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { useGetContactsQuery } from "services/contact";

function Home() {
  const [page] = useState(1);
  const { data, isLoading } = useGetContactsQuery({ page });
  const router = useRouter();

  if (isLoading) {
    return Array.from({ length: 10 }).map((_, i) => (
      <Stack key={i} my={2} justifyContent="center" alignItems="center" px={3}>
        <Skeleton variant="rectangular" width="100%" height={118} />
      </Stack>
    ));
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="sm">
        <Stack divider={<Divider />}>
          {data.results.map((contact) => {
            return (
              <Stack key={contact.id} my={2} px={3}>
                <Stack spacing={1}>
                  <Typography>
                    {contact.firstName} {contact.lastName}
                  </Typography>
                  <Typography>{contact.email}</Typography>
                  <Typography>{contact.phone}</Typography>
                </Stack>
                <Stack
                  direction={["column", "row"]}
                  spacing={[1, 2]}
                  pt={[0, 2]}
                >
                  <Button
                    variant="outlined"
                    onClick={() => {
                      router.push(`/contact/${contact.id}`);
                    }}
                  >
                    Editar
                  </Button>
                  <Button>Eliminar</Button>
                </Stack>
              </Stack>
            );
          })}
        </Stack>
      </Container>
    </div>
  );
}

export default Home;
